# Generated by Django 4.1.3 on 2022-12-22 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0002_designation_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('designation_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sms_app.designation')),
                ('duration_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sms_app.duration')),
            ],
        ),
    ]
